issues:
        max-same-issues: 0
        exclude-use-default: false
linters:
        enable:
        - misspell
        - gofumpt
        - staticcheck
        - unused
        - typecheck
        - ineffassign
        - errcheck
        - gosimple
        - goconst
        - zerologlint
        - sqlclosecheck
        - bodyclose
        - dupl
        - revive

linters-settings:
