FROM vocdoni/go-dvote:latest

ENV COMPONENT_VERSION=2.04

WORKDIR /app

COPY . .

RUN go build -o miner cmd/miner/miner.go && \
 apk del build-base git binutils binutils-gold linux-headers openssl && \
 rm -rf /root/go
 
CMD /app/dockerfiles/miner/files/minerStart.sh
