FROM golang:alpine

ENV COMPONENT_VERSION=1.24

WORKDIR /app

RUN apk update && apk add --no-cache build-base git binutils \
 binutils-gold libc6-compat ca-certificates openssl linux-headers && \
 git clone https://gitlab.com/vocdoni/go-dvote.git/ . && go mod download && rm -rf /app
 
CMD /bin/sh
