{
 "title": "Vocdoni testsuite",
 "tags": [ "prod" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{environment=\"test\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{environment=\"test\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{environment=\"test\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory average 6h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(process_resident_memory_bytes{environment=\"test\"}[6h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "description": "Open Files",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{environment=\"test\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go threads by server type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_threads{environment=\"test\"}) by (job)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Vochain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Vochain Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{environment=\"test\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "vochain_mempool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vochain_mempool{environment=\"test\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Votes per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(vochain_vote_tree{instance=\"miner1.vocdoni.net:9090\"}[1m])",
     "legendFormat": "{{instance}} votes/minute"
    }
   ]
  },
  {
   "title": "block interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "60/delta(tendermint_consensus_block_interval_seconds_count{instance=\"miner2.dev.vocdoni.net:9090\"}[60s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "vochain_height",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vochain_height{environment=\"test\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Vochain Total Number of Votes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vochain_vote_tree{environment=\"test\",instance=\"miner1.vocdoni.net:9090\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus block interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds{instance=\"miner1.vocdoni.net:9090\"}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "API publicReqs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "idelta(router_public_reqs{environment=\"test\",method=\"getBlockStatus\"}[1m])",
     "legendFormat": "{{instance}} {{method}}"
    }
   ]
  },
  {
   "title": "Census",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "census_loaded {environment=\"test\"}",
     "legendFormat": "loaded {{instance}}"
    }
   ]
  },
  {
   "title": "vochain_process_tree",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vochain_process_tree{environment=\"test\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Registry backend events",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "registry_requests{environment=\"test\"}",
     "legendFormat": "{{method}}"
    },
    {}
   ]
  },
  {
   "title": "API privateReqs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "router_private_reqs{environment=\"test\"}",
     "legendFormat": "{{instance}} {{method}}"
    }
   ]
  },
  { "title": "IPFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "file_addresses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "file_addresses{environment=\"test\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "file_pins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "file_pins{environment=\"test\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "file_peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "file_peers{environment=\"test\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}