// Code generated by "stringer -type CurrentProcessState"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Scheduled-0]
	_ = x[Active-1]
	_ = x[Paused-2]
	_ = x[Finished-3]
	_ = x[Canceled-4]
}

const _CurrentProcessState_name = "ScheduledActivePausedFinishedCanceled"

var _CurrentProcessState_index = [...]uint8{0, 9, 15, 21, 29, 37}

func (i CurrentProcessState) String() string {
	if i < 0 || i >= CurrentProcessState(len(_CurrentProcessState_index)-1) {
		return "CurrentProcessState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CurrentProcessState_name[_CurrentProcessState_index[i]:_CurrentProcessState_index[i+1]]
}
