{
 "title": "metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Votes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vochain_vote_tree_increase_last_minute{instance=\"miner0:9090\"}/60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Vote cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "vochain_vote_cache{environment=\"test\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(tendermint_consensus_block_size_bytes_sum{instance=\"miner0:9090\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "60/delta(tendermint_consensus_block_interval_seconds_count{environment=\"test\"}[60s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transactions per minute",
   "type": "timeseries",
   "description": "Transactions per minute",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(delta(tendermint_consensus_total_txs{instance=\"miner0:9090\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{environment=\"test\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{environment=\"test\"}/1024/1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blockchain height",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vochain_height{environment=\"test\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}