services:
  gateway:
    build:
      context: ../../
    image: "ghcr.io/vocdoni/voconed:${IMAGE_TAG:-main}"
    entrypoint: "/app/voconed"
    env_file: .env
    volumes:
      - "run:/app/run"
    ports:
      - "${VOCONED_PORT}:${VOCONED_PORT}"
    sysctls:
      net.core.somaxconn: 8128
    restart: ${RESTART:-no}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.routers.gateway.service=gateway"
      - "traefik.http.routers.gateway.rule=(PathPrefix(`${VOCONED_URLPATH}`))"
      - "traefik.http.services.gateway.loadbalancer.server.port=${VOCONED_PORT}"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

  traefik:
    image: traefik:2.3
    ports:
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

volumes:
  vocexplorer: {}
  run: {}
