// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: account.sql

package indexerdb

import (
	"context"
	"database/sql"

	"go.vocdoni.io/dvote/types"
)

const countAccounts = `-- name: CountAccounts :one
SELECT COUNT(*) FROM accounts
`

func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countAccountsStmt, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :execresult
INSERT INTO accounts (
    account, balance, nonce
) VALUES (?, ?, ?)
ON CONFLICT(account) DO UPDATE
SET balance = excluded.balance,
    nonce   = excluded.nonce
`

type CreateAccountParams struct {
	Account types.AccountID
	Balance int64
	Nonce   int64
}

// Preserves name/avatar (resolved separately by SetAccountMetadata): a plain
// REPLACE INTO is DELETE + INSERT, so every account update would otherwise wipe
// them back to their defaults.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (sql.Result, error) {
	return q.exec(ctx, q.createAccountStmt, createAccount, arg.Account, arg.Balance, arg.Nonce)
}

const listAccountsMissingName = `-- name: ListAccountsMissingName :many
SELECT account FROM accounts
WHERE name = '' AND account > ?1
ORDER BY account
LIMIT ?2
`

type ListAccountsMissingNameParams struct {
	AfterAccount types.AccountID
	Limit        int64
}

// Lists the accounts whose name was never resolved, so a backfill knows which
// ones to look up. Used once per boot. Paged by the account id rather than by an
// offset, so that a page is never revisited even though rows leave the result set
// as the backfill fills them.
func (q *Queries) ListAccountsMissingName(ctx context.Context, arg ListAccountsMissingNameParams) ([]types.AccountID, error) {
	rows, err := q.query(ctx, q.listAccountsMissingNameStmt, listAccountsMissingName, arg.AfterAccount, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []types.AccountID
	for rows.Next() {
		var account types.AccountID
		if err := rows.Scan(&account); err != nil {
			return nil, err
		}
		items = append(items, account)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAccounts = `-- name: SearchAccounts :many
WITH results AS (
  SELECT account, balance, nonce, name, avatar
  FROM accounts
  WHERE (
    (
    ?3 = ''
    OR (LENGTH(?3) = 40 AND LOWER(HEX(account)) = LOWER(?3))
    OR (LENGTH(?3) < 40 AND INSTR(LOWER(HEX(account)), LOWER(?3)) > 0)
    -- TODO: consider keeping an account_hex column for faster searches
    )
  )
)
SELECT account, balance, nonce, name, avatar, COUNT(*) OVER() AS total_count
FROM results
ORDER BY balance DESC
LIMIT ?2
OFFSET ?1
`

type SearchAccountsParams struct {
	Offset          int64
	Limit           int64
	AccountIDSubstr interface{}
}

type SearchAccountsRow struct {
	Account    []byte
	Balance    int64
	Nonce      int64
	Name       string
	Avatar     string
	TotalCount int64
}

func (q *Queries) SearchAccounts(ctx context.Context, arg SearchAccountsParams) ([]SearchAccountsRow, error) {
	rows, err := q.query(ctx, q.searchAccountsStmt, searchAccounts, arg.Offset, arg.Limit, arg.AccountIDSubstr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAccountsRow
	for rows.Next() {
		var i SearchAccountsRow
		if err := rows.Scan(
			&i.Account,
			&i.Balance,
			&i.Nonce,
			&i.Name,
			&i.Avatar,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountMetadata = `-- name: SetAccountMetadata :execresult
UPDATE accounts
SET name = ?1,
    avatar = ?2
WHERE account = ?3
  AND (name != ?1 OR avatar != ?2)
`

type SetAccountMetadataParams struct {
	Name    string
	Avatar  string
	Account types.AccountID
}

// Stores the name and avatar resolved from the account off-chain metadata. Only
// writes when either actually changed, so re-resolving unchanged metadata costs
// no write. The account row must exist; accounts are created by CreateAccount
// when the state indexes them.
func (q *Queries) SetAccountMetadata(ctx context.Context, arg SetAccountMetadataParams) (sql.Result, error) {
	return q.exec(ctx, q.setAccountMetadataStmt, setAccountMetadata, arg.Name, arg.Avatar, arg.Account)
}
