// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: blocks.sql

package indexerdb

import (
	"context"
	"database/sql"
	"time"
)

const createBlock = `-- name: CreateBlock :execresult
INSERT INTO blocks(
    chain_id, height, time, hash, proposer_address, last_block_hash
) VALUES (
	?, ?, ?, ?, ?, ?
)
`

type CreateBlockParams struct {
	ChainID         string
	Height          int64
	Time            time.Time
	Hash            []byte
	ProposerAddress []byte
	LastBlockHash   []byte
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (sql.Result, error) {
	return q.exec(ctx, q.createBlockStmt, createBlock,
		arg.ChainID,
		arg.Height,
		arg.Time,
		arg.Hash,
		arg.ProposerAddress,
		arg.LastBlockHash,
	)
}

const getBlock = `-- name: GetBlock :one
SELECT height, time, chain_id, hash, proposer_address, last_block_hash FROM blocks
WHERE height = ?
LIMIT 1
`

func (q *Queries) GetBlock(ctx context.Context, height int64) (Block, error) {
	row := q.queryRow(ctx, q.getBlockStmt, getBlock, height)
	var i Block
	err := row.Scan(
		&i.Height,
		&i.Time,
		&i.ChainID,
		&i.Hash,
		&i.ProposerAddress,
		&i.LastBlockHash,
	)
	return i, err
}
