// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package indexerdb

import (
	"time"

	"go.vocdoni.io/dvote/types"
	"go.vocdoni.io/dvote/vochain/state"
)

type Block struct {
	Height   int64
	Time     time.Time
	DataHash []byte
}

type Process struct {
	ID                    types.ProcessID
	EntityID              types.EntityID
	StartBlock            int64
	EndBlock              int64
	ResultsHeight         int64
	HaveResults           bool
	FinalResults          bool
	ResultsVotes          string
	ResultsWeight         string
	ResultsEnvelopeHeight int64
	ResultsBlockHeight    int64
	CensusRoot            types.CensusRoot
	RollingCensusRoot     types.CensusRoot
	RollingCensusSize     int64
	MaxCensusSize         int64
	CensusUri             string
	Metadata              string
	CensusOrigin          int64
	Status                int64
	Namespace             int64
	EnvelopePb            types.EncodedProtoBuf
	ModePb                types.EncodedProtoBuf
	VoteOptsPb            types.EncodedProtoBuf
	PrivateKeys           string
	PublicKeys            string
	QuestionIndex         int64
	CreationTime          time.Time
	SourceBlockHeight     int64
	SourceNetworkID       int64
}

type TokenTransfer struct {
	TxHash       types.Hash
	BlockHeight  int64
	FromAccount  types.AccountID
	ToAccount    types.AccountID
	Amount       int64
	TransferTime time.Time
}

type Transaction struct {
	ID          int64
	Hash        types.Hash
	BlockHeight int64
	BlockIndex  int64
	Type        string
}

type Vote struct {
	Nullifier      types.Nullifier
	ProcessID      types.ProcessID
	BlockHeight    int64
	BlockIndex     int64
	Weight         string
	CreationTime   time.Time
	VoterID        state.VoterID
	OverwriteCount int64
}
