// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package indexerdb

import (
	"database/sql"
	"time"

	"go.vocdoni.io/dvote/types"
)

type Account struct {
	Account types.AccountID
	Balance int64
	Nonce   int64
}

type Block struct {
	Height   int64
	Time     time.Time
	DataHash []byte
}

type Process struct {
	ID                 types.ProcessID
	EntityID           types.EntityID
	StartDate          time.Time
	EndDate            time.Time
	ManuallyEnded      bool
	BlockCount         sql.NullInt64
	VoteCount          int64
	ChainID            string
	HaveResults        bool
	FinalResults       bool
	ResultsVotes       string
	ResultsWeight      string
	ResultsBlockHeight int64
	CensusRoot         types.CensusRoot
	MaxCensusSize      int64
	CensusUri          string
	Metadata           string
	CensusOrigin       int64
	Status             int64
	Namespace          int64
	Envelope           string
	Mode               string
	VoteOpts           string
	PrivateKeys        string
	PublicKeys         string
	QuestionIndex      int64
	CreationTime       time.Time
	SourceBlockHeight  int64
	SourceNetworkID    int64
	FromArchive        bool
}

type TokenFee struct {
	ID          int64
	BlockHeight int64
	FromAccount []byte
	Reference   string
	Cost        int64
	TxType      string
	SpendTime   time.Time
}

type TokenTransfer struct {
	TxHash       types.Hash
	BlockHeight  int64
	FromAccount  types.AccountID
	ToAccount    types.AccountID
	Amount       int64
	TransferTime time.Time
}

type Transaction struct {
	ID          int64
	Hash        types.Hash
	BlockHeight int64
	BlockIndex  int64
	Type        string
}
