// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: vote_reference.sql

package indexerdb

import (
	"context"
	"database/sql"
	"time"

	"go.vocdoni.io/dvote/types"
	"go.vocdoni.io/dvote/vochain/state"
)

const createVoteReference = `-- name: CreateVoteReference :execresult
REPLACE INTO vote_references (
	nullifier, process_id, height, weight,
	tx_index, voter_id, overwrite_count, creation_time
) VALUES (
	?, ?, ?, ?,
	?, ?, ?, ?
)
`

type CreateVoteReferenceParams struct {
	Nullifier      types.Nullifier
	ProcessID      types.ProcessID
	Height         int64
	Weight         string
	TxIndex        int64
	VoterID        state.VoterID
	OverwriteCount int64
	CreationTime   time.Time
}

func (q *Queries) CreateVoteReference(ctx context.Context, arg CreateVoteReferenceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createVoteReference,
		arg.Nullifier,
		arg.ProcessID,
		arg.Height,
		arg.Weight,
		arg.TxIndex,
		arg.VoterID,
		arg.OverwriteCount,
		arg.CreationTime,
	)
}

const getVoteReference = `-- name: GetVoteReference :one
SELECT vote_references.nullifier, vote_references.process_id, vote_references.height, vote_references.weight, vote_references.tx_index, vote_references.creation_time, vote_references.voter_id, vote_references.overwrite_count, tx_references.hash FROM vote_references
LEFT JOIN tx_references
	ON vote_references.height = tx_references.block_height
	AND vote_references.tx_index = tx_references.tx_block_index
WHERE nullifier = ?
LIMIT 1
`

type GetVoteReferenceRow struct {
	Nullifier      types.Nullifier
	ProcessID      types.ProcessID
	Height         int64
	Weight         string
	TxIndex        int64
	CreationTime   time.Time
	VoterID        state.VoterID
	OverwriteCount int64
	Hash           types.Hash
}

func (q *Queries) GetVoteReference(ctx context.Context, nullifier types.Nullifier) (GetVoteReferenceRow, error) {
	row := q.db.QueryRowContext(ctx, getVoteReference, nullifier)
	var i GetVoteReferenceRow
	err := row.Scan(
		&i.Nullifier,
		&i.ProcessID,
		&i.Height,
		&i.Weight,
		&i.TxIndex,
		&i.CreationTime,
		&i.VoterID,
		&i.OverwriteCount,
		&i.Hash,
	)
	return i, err
}

const searchVoteReferences = `-- name: SearchVoteReferences :many
SELECT vote_references.nullifier, vote_references.process_id, vote_references.height, vote_references.weight, vote_references.tx_index, vote_references.creation_time, vote_references.voter_id, vote_references.overwrite_count, tx_references.hash FROM vote_references
LEFT JOIN tx_references
	ON vote_references.height = tx_references.block_height
	AND vote_references.tx_index = tx_references.tx_block_index
WHERE (? = '' OR process_id = ?)
	AND (? = '' OR (INSTR(LOWER(HEX(nullifier)), ?) > 0))
ORDER BY height DESC, nullifier ASC
LIMIT ?
OFFSET ?
`

type SearchVoteReferencesParams struct {
	ProcessID       types.ProcessID
	NullifierSubstr string
	Limit           int32
	Offset          int32
}

type SearchVoteReferencesRow struct {
	Nullifier      types.Nullifier
	ProcessID      types.ProcessID
	Height         int64
	Weight         string
	TxIndex        int64
	CreationTime   time.Time
	VoterID        state.VoterID
	OverwriteCount int64
	Hash           types.Hash
}

func (q *Queries) SearchVoteReferences(ctx context.Context, arg SearchVoteReferencesParams) ([]SearchVoteReferencesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchVoteReferences,
		arg.ProcessID,
		arg.ProcessID,
		arg.NullifierSubstr,
		arg.NullifierSubstr,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchVoteReferencesRow
	for rows.Next() {
		var i SearchVoteReferencesRow
		if err := rows.Scan(
			&i.Nullifier,
			&i.ProcessID,
			&i.Height,
			&i.Weight,
			&i.TxIndex,
			&i.CreationTime,
			&i.VoterID,
			&i.OverwriteCount,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
