// Code generated by "stringer -linecomment -type APIError"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrAddressMalformed-4000]
	_ = x[ErrDstAddressMalformed-4001]
	_ = x[ErrDstAccountUnknown-4002]
	_ = x[ErrAccountNotFound-4003]
	_ = x[ErrAccountAlreadyExists-4004]
	_ = x[ErrTreasurerNotFound-4005]
	_ = x[ErrOrgNotFound-4006]
	_ = x[ErrTransactionNotFound-4007]
	_ = x[ErrBlockNotFound-4008]
	_ = x[ErrMetadataProvidedButNoURI-4009]
	_ = x[ErrMetadataURINotMatchContent-4010]
	_ = x[ErrMarshalingJSONFailed-4011]
	_ = x[ErrFileSizeTooBig-4012]
	_ = x[ErrCantParseOrgID-4013]
	_ = x[ErrCantParseAccountID-4014]
	_ = x[ErrCantParseBearerToken-4015]
	_ = x[ErrCantParseDataAsJSON-4016]
	_ = x[ErrCantParseElectionID-4017]
	_ = x[ErrCantParseMetadataAsJSON-4018]
	_ = x[ErrCantParsePageNumber-4019]
	_ = x[ErrCantParsePayloadAsJSON-4020]
	_ = x[ErrCantParseVoteID-4021]
	_ = x[ErrCantExtractMetadataURI-4022]
	_ = x[ErrVoteIDMalformed-4023]
	_ = x[ErrVoteNotRegistered-4024]
	_ = x[ErrCensusIDLengthInvalid-4025]
	_ = x[ErrCensusRootIsNil-4026]
	_ = x[ErrCensusTypeUnknown-4027]
	_ = x[ErrCensusTypeMismatch-4028]
	_ = x[ErrCensusIndexedFlagMismatch-4029]
	_ = x[ErrCensusRootHashMismatch-4030]
	_ = x[ErrParamStatusMissing-4031]
	_ = x[ErrParamParticipantsMissing-4032]
	_ = x[ErrParamParticipantsTooBig-4033]
	_ = x[ErrParamDumpOrRootMissing-4034]
	_ = x[ErrParamKeyOrProofMissing-4035]
	_ = x[ErrParamRootInvalid-4036]
	_ = x[ErrParamNetworkInvalid-4037]
	_ = x[ErrParamToInvalid-4038]
	_ = x[ErrParticipantKeyMissing-4039]
	_ = x[ErrIndexedCensusCantUseWeight-4040]
	_ = x[ErrWalletNotFound-4041]
	_ = x[ErrWalletPrivKeyAlreadyExists-4042]
	_ = x[ErrElectionEndDateInThePast-4043]
	_ = x[ErrElectionEndDateBeforeStart-4044]
	_ = x[ErrVochainEmptyReply-5000]
	_ = x[ErrVochainSendTxFailed-5001]
	_ = x[ErrVochainGetTxFailed-5002]
	_ = x[ErrVochainReturnedErrorCode-5003]
	_ = x[ErrVochainReturnedInvalidElectionID-5004]
	_ = x[ErrVochainReturnedWrongMetadataCID-5005]
	_ = x[ErrMarshalingServerJSONFailed-5006]
	_ = x[ErrCantFetchElectionList-5007]
	_ = x[ErrCantFetchElection-5008]
	_ = x[ErrCantFetchElectionResults-5009]
	_ = x[ErrCantFetchTokenTransfers-5010]
	_ = x[ErrCantFetchEnvelopeHeight-5011]
	_ = x[ErrCantFetchEnvelope-5012]
	_ = x[ErrCantCheckTxType-5013]
	_ = x[ErrCantABIEncodeResults-5014]
	_ = x[ErrCantComputeKeyHash-5015]
	_ = x[ErrCantAddKeyAndValueToTree-5016]
	_ = x[ErrCantAddKeyToTree-5017]
	_ = x[ErrCantGenerateFaucetPkg-5018]
	_ = x[ErrCantEstimateBlockHeight-5019]
	_ = x[ErrCantMarshalMetadata-5020]
	_ = x[ErrCantPublishMetadata-5021]
	_ = x[ErrTxTypeMismatch-5022]
	_ = x[ErrElectionIsNil-5023]
	_ = x[ErrElectionResultsNotYetAvailable-5024]
	_ = x[ErrElectionResultsIsNil-5025]
	_ = x[ErrElectionResultsMismatch-5026]
	_ = x[ErrMissingModulesForHandler-5027]
	_ = x[ErrHandlerUnknown-5028]
	_ = x[ErrHTTPRouterIsNil-5029]
	_ = x[ErrBaseRouteInvalid-5030]
}

const (
	_APIError_name_0 = "address malformeddestination address malformeddestination account is unknownaccount not foundaccount already existstreasurer account not foundorganization not foundtransaction hash not foundblock not foundmetadata provided but no metadata URI found in transactionmetadata URI does not match metadata contentmarshaling JSON failedfile size exceeds the maximum allowedcannot parse organizationIDcannot parse accountIDcannot parse bearer tokencannot parse data as JSONcannot parse electionIDcannot parse metadata (invalid format)cannot parse page numbercannot parse payload as JSONcannot parse voteIDcannot extract metadata URIvoteID is malformedvote not registeredcensusID length is wrongcensus root is nilcensus type is unknowncensus type mismatchcensus indexed flag mismatchcensus root hash mismatch after importing dumpparameter (status) missing or invalidparameter (participants) missingparameter (participants) exceeds max length per callparameter (dump or root) missingparameter (key or proof) missingparameter (root) invalidinvalid networkinvalid addressmissing participant keyindexed census cannot use weightwallet not foundwallet private key already existselection end date cannot be in the pastelection end date must be after start date"
	_APIError_name_1 = "vochain returned an empty replyvochain SendTx failedvochain GetTx failedvochain replied with error codevochain returned an invalid electionID after executing txvochain returned an unexpected metadata CID after executing txmarshaling (server-side) JSON failedcannot fetch election listcannot fetch electioncannot fetch election resultscannot fetch token transferscannot fetch envelope heightcannot fetch vote envelopecannot check transaction typecannot abi.encode resultscannot compute key hashcannot add key and value to treecannot add key to treecannot generate faucet packagecannot estimate startDate block heightcannot marshal metadatacannot publish metadata filetransaction type mismatchelection is nilelection results are not yet availableelection results is nilelection results don't match reported onesmissing modules attached for enabling handlerhandler unknownhttprouter is nilbase route must start with /"
)

var (
	_APIError_index_0 = [...]uint16{0, 17, 46, 76, 93, 115, 142, 164, 190, 205, 263, 307, 329, 366, 393, 415, 440, 465, 488, 526, 550, 578, 597, 624, 643, 662, 686, 704, 726, 746, 774, 820, 857, 889, 941, 973, 1005, 1029, 1044, 1059, 1082, 1114, 1130, 1163, 1202, 1244}
	_APIError_index_1 = [...]uint16{0, 31, 52, 72, 103, 160, 222, 258, 284, 305, 334, 362, 390, 416, 445, 470, 493, 525, 547, 577, 615, 638, 666, 691, 706, 744, 767, 809, 854, 869, 886, 914}
)

func (i APIError) String() string {
	switch {
	case 4000 <= i && i <= 4044:
		i -= 4000
		return _APIError_name_0[_APIError_index_0[i]:_APIError_index_0[i+1]]
	case 5000 <= i && i <= 5030:
		i -= 5000
		return _APIError_name_1[_APIError_index_1[i]:_APIError_index_1[i+1]]
	default:
		return "APIError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
