name: Deploy dev

on:
  push:
    branches:
      - main
      - dev

jobs:
  push-to-dev:
    name: Git push main -> dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # the push step needs a full repo, not shallow
    - name: Push main branch to dev branch
      run: git push origin main:dev

  call-docker-release:
    name: Docker
    needs: push-to-dev
    if: always() && !cancelled() && !failure() # so if push-to-dev was skipped (because branch is dev) this still runs
    uses: vocdoni/vocdoni-node/.github/workflows/docker-release.yml@main
    secrets: inherit
    with:
      image-tag: dev
