---
name: Deploy dev

on:
  push:
    branches:
      - main

jobs:
  push-to-dev:
    name: Git push main -> dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # the push step needs a full repo, not shallow
    - name: Push main branch to dev branch
      run: git push origin main:dev

  call-docker-release:
    name: Docker
    needs: push-to-dev
    uses: vocdoni/vocdoni-node/.github/workflows/docker-release.yml@main
    secrets: inherit
    with:
      image-tag: dev
